name: CD

on:
  push:
    branches: [alpha]

jobs:
  cd:
    name: Build and deploy docs to GitHub Pages

    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v7

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
          run-install: true

      - name: Release
        run: vpr release

      - name: Pack
        run: vpr pack:docs

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/.vitepress/dist/

  deploy:
    permissions:
      pages: write
      id-token: write
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    needs: cd
    steps:
      - name: Release
        run: vpr release

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
